### PR TITLE
Implementation of {CBN, CBV, FullBeta} redex strategies

### PR DESCRIPTION
**Pull request by graymalkin**

### CODE REVIEW

**Comment by dorchard** [comment]
Awesome! Thanks!

**Comment by dorchard** [comment]
The idiomatic way of doing infix `fmap` is  to use `<$>` instead btw.

**Comment by graymalkin** [comment]
Ah, I'll tweak that and update the pull request.

It wasn't listed on the fmap documentation, annoyingly.

(at least in the place I was looking)

http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Functor.html

- Simon

**Comment by graymalkin** [comment]
I didn't read the docs properly apparently. Anyway, updated.

**Comment by dorchard** [comment]
Excellent. I really like this structuring in the end.

**Pull request merged**
